site_name: Twilio Microphone Test App
site_description: A simple service for testing microphone quality over VoIP calls
repo_url: https://github.com/yourusername/twilio-mic-test
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: 
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Deployment:
    - Azure: deployment/azure.md
    - Other Options: deployment/other-options.md
  - API Reference: api-reference.md
  - Twilio Setup: twilio-setup.md